// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package db

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DBEngineClient is the client API for DBEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DBEngineClient interface {
	CustomQuery(ctx context.Context, in *CustomCommandReq, opts ...grpc.CallOption) (*CustomCommandRes, error)
}

type dBEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewDBEngineClient(cc grpc.ClientConnInterface) DBEngineClient {
	return &dBEngineClient{cc}
}

func (c *dBEngineClient) CustomQuery(ctx context.Context, in *CustomCommandReq, opts ...grpc.CallOption) (*CustomCommandRes, error) {
	out := new(CustomCommandRes)
	err := c.cc.Invoke(ctx, "/db.DBEngine/CustomQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBEngineServer is the server API for DBEngine service.
// All implementations must embed UnimplementedDBEngineServer
// for forward compatibility
type DBEngineServer interface {
	CustomQuery(context.Context, *CustomCommandReq) (*CustomCommandRes, error)
	mustEmbedUnimplementedDBEngineServer()
}

// UnimplementedDBEngineServer must be embedded to have forward compatible implementations.
type UnimplementedDBEngineServer struct {
}

func (UnimplementedDBEngineServer) CustomQuery(context.Context, *CustomCommandReq) (*CustomCommandRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomQuery not implemented")
}
func (UnimplementedDBEngineServer) mustEmbedUnimplementedDBEngineServer() {}

// UnsafeDBEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBEngineServer will
// result in compilation errors.
type UnsafeDBEngineServer interface {
	mustEmbedUnimplementedDBEngineServer()
}

func RegisterDBEngineServer(s grpc.ServiceRegistrar, srv DBEngineServer) {
	s.RegisterService(&DBEngine_ServiceDesc, srv)
}

func _DBEngine_CustomQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomCommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBEngineServer).CustomQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.DBEngine/CustomQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBEngineServer).CustomQuery(ctx, req.(*CustomCommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DBEngine_ServiceDesc is the grpc.ServiceDesc for DBEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "db.DBEngine",
	HandlerType: (*DBEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CustomQuery",
			Handler:    _DBEngine_CustomQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db.proto",
}
