// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package params

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ParamReaderClient is the client API for ParamReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParamReaderClient interface {
	GetParam(ctx context.Context, in *RequestParam, opts ...grpc.CallOption) (*ResponseParam, error)
}

type paramReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewParamReaderClient(cc grpc.ClientConnInterface) ParamReaderClient {
	return &paramReaderClient{cc}
}

func (c *paramReaderClient) GetParam(ctx context.Context, in *RequestParam, opts ...grpc.CallOption) (*ResponseParam, error) {
	out := new(ResponseParam)
	err := c.cc.Invoke(ctx, "/params.ParamReader/getParam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParamReaderServer is the server API for ParamReader service.
// All implementations must embed UnimplementedParamReaderServer
// for forward compatibility
type ParamReaderServer interface {
	GetParam(context.Context, *RequestParam) (*ResponseParam, error)
	mustEmbedUnimplementedParamReaderServer()
}

// UnimplementedParamReaderServer must be embedded to have forward compatible implementations.
type UnimplementedParamReaderServer struct {
}

func (UnimplementedParamReaderServer) GetParam(context.Context, *RequestParam) (*ResponseParam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParam not implemented")
}
func (UnimplementedParamReaderServer) mustEmbedUnimplementedParamReaderServer() {}

// UnsafeParamReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParamReaderServer will
// result in compilation errors.
type UnsafeParamReaderServer interface {
	mustEmbedUnimplementedParamReaderServer()
}

func RegisterParamReaderServer(s grpc.ServiceRegistrar, srv ParamReaderServer) {
	s.RegisterService(&ParamReader_ServiceDesc, srv)
}

func _ParamReader_GetParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParamReaderServer).GetParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/params.ParamReader/getParam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParamReaderServer).GetParam(ctx, req.(*RequestParam))
	}
	return interceptor(ctx, in, info, handler)
}

// ParamReader_ServiceDesc is the grpc.ServiceDesc for ParamReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParamReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "params.ParamReader",
	HandlerType: (*ParamReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getParam",
			Handler:    _ParamReader_GetParam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "params.proto",
}
